config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'
  get 'about' => 'pages#about'
  get 'feedback' => 'pages#feedback'
  get 'userprofiles/:id' => 'userprofiles#show', as: :userprofiles
  get 'admin' => 'admin#index'
  get 'users/:id/approve'=> 'users#approve_user', as: 'approve_user'
  get 'users/:id/unapprove'=> 'users#unapprove_user', as: 'unapprove_user'
  get 'church' => 'pages#church'
  get 'neighborhood' => 'pages#neighborhood'
  resources :conversations do
    resources :messages
  end

end

app/views/admin/index.html.erb
<div class="well", overflow="auto">
	<% if user_signed_in? && current_user && current_user.admin? %>
		<h2>Admin Panel</h2>	
		<p></p>
		<div class="panel panel-default">
			<div class="panel-heading">User Approvals</div>
			<div class="panel-body"></div>
			<div class="admin-panel">
			 	<table class="table table-striped">
			 		<thead>
			 			<tr>
				 			<th>Created</th>
				 			<th>Profile pic</th>
				 			<th>Full name</th>
				 			<th>Gender</th>
				 			<th>Age</th>
				 			<th>Height</th>
				 			<th>Church</th>
				 			<th>Church status</th>
				 			<th>Neighbhorhood</th>
				 			<th>Confirmed</th>
				 			<th>Admin?</th>
				 			<th>Approved?</th>
				 			<th>Cellphone</th>
				 			<th>Email</th>
				 			<th>DOB</th>
				 			<th>Updated</th>
				 		</tr>
			 		</thead>
			 		<tbody>
			 			<% @user.each do |user| %>
				 			<tr>
			    			<td>
			    				<% if user.created_at != nil %>
			    					<%= user.created_at.strftime("%m/%d/%y") %>
			    				<% end %>	
			    			</td>
			    			<td><%= image_tag user.avatar.url(:small), class: "img-thumbnail" %></td>
			    			<td><%= link_to "#{user.first_name} #{user.last_name}", userprofiles_path(user)%>
			    			<td>
			    				<% if user.is_female == true %>
										Female
									<% else %>
										Male
									<% end %>	
			    			</td>
			    			<td> <!--Age -->
			    				<%= Time.now.utc.to_date.year - user.date_of_birth.year - (user.date_of_birth.to_date.change(:year => Time.now.utc.to_date.year) > Time.now.utc.to_date ? 1 : 0)%>
			    			</td>
			    			<td><%= user.height / 12 %>'-<%= user.height % 12 %></td>
			    			<td><%= user.church %></td>
			    			<td><%= user.church_status %></td>
			    			<td><%= user.neighborhood %></td>
			    			<td>
			    				<% if user.confirmed_at != nil %>
			    					<%= user.confirmed_at.strftime("%m/%d/%y") %>
			    				<% end %>	
			    			</td>
			    			<td>
			    				<% if user.admin == true %>
										<b>*ADMIN*</b>
									<% else %>
										<i>---no---</i>
									<% end %>			    				
			    			</td>
			    			<td>
			    				<% if user.approved == true %>
										<b>*APPROVED*</b> 
										<% if user.admin == false %> 
											[<i><%= link_to "unapprove", unapprove_user_path(user) %></i>]
										<% end %>
									<% else %>
										<i>--no--</i> [<b><%= link_to "*APPROVE*", approve_user_path(user) %></b>]
									<% end %>	
			    			</td>
			    			<td><%= user.cellphone %></td>
			    			<td><%= user.email %></td>
			    			<td>
			    				<% if user.updated_at != nil %>
			    					<%= user.updated_at.strftime("%m/%d/%y") %>
			    				<% end %>	
			    			</td>
			    			<td><%= user.date_of_birth.strftime("%m/%d/%y") %></td>
		    			</tr>
	    			<% end %>
					</tbody>
	  		</table>
	  	</div>
		</div>
	<% end %>
</div>