config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'
  get 'about' => 'pages#about'
  get 'feedback' => 'pages#feedback'
  get 'userprofiles/:id' => 'userprofiles#show', as: :userprofiles
  get 'admin' => 'admin#index'
  get 'users/:id/approve'=> 'users#approve_user', as: 'approve_user'
  get 'users/:id/unapprove'=> 'users#unapprove_user', as: 'unapprove_user'
  get 'church' => 'pages#church'
  get 'neighborhood' => 'pages#neighborhood'
  resources :conversations do
    resources :messages
  end

end

app/views/pages/_user_index.html.erb
<% @user.each do |user| %>
	<h2>the ello community at: <%= @user.church %> </h2>	
		<p></p>
	<div class="panel panel-info">
		<div class="panel-heading">
			<h3 class="panel-title">
				<%= user.first_name %> <%= user.last_name[0,1] %>. <%= link_to 'Send Msg', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post', class: 'btn btn-info btn-xs pull-right' %>
			</h3> 
		</div>
		<div class="panel-body">
	  	<table class="table table-bordered">
	  		<tbody>
	  			<tr>
	  				<th scope="row">Church</th>
	  				<td align="left"><%= user.church %>, <%= user.church_status %></td>
	  			</tr>
	  			<tr>
	  				<th scope="row">Interests</th>
	  				<td align="left"><%= user.interests %></td>
	  			</tr>
	  			<tr>
	  				<th scope="row">Testimony/Faith</th>
	  				<td align="left"><%= user.testimony %></td>
	  			</tr>
	  			<tr>
	  				<th scope="row">My Story</th>
	  				<td align="left"><%= user.more_info %></td>
	  			</tr>
	  		</tbody>
			</table>
		</div>
		<div class="panel-footer">
			<div class="row"><%= image_tag user.avatar.url(:thumb), class: "img-thumbnail" %></div>
			<p></p>
			<div class="row">
				<% if user.is_female == true %>
					Female,
				<% else %>
					Male,
				<% end %>
					Age: <%= Time.now.utc.to_date.year - user.date_of_birth.year - (user.date_of_birth.to_date.change(:year => Time.now.utc.to_date.year) > Time.now.utc.to_date ? 1 : 0)%>,
						Height: <%= user.height / 12 %>'-<%= user.height % 12 %>"<br/>
						<%= user.neighborhood %>
			</div>
		</div>
	</div>
<% end %>

app/views/pages/about.html.erb
<div class="jumbotron center">
	<h1>about</h1>
	<p>ello = short for hello</p>
	<% if user_signed_in? %>
	<p>ello is a platform to connect believers and foster community across the city</p>
	<% end %>
</div>

app/views/pages/church.html.erb
<div class="jumbotron center">
	<% if user_signed_in? %>
		<h2>ello @ <%= params[:church] %></h2>	
		<p></p>
  	<% @user.each do |user| %>
			<div class="panel panel-info">
				<div class="panel-heading">
					<h3 class="panel-title">
						<%= user.first_name %> <%= user.last_name[0,1] %>. <%= link_to 'Send Msg', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post', class: 'btn btn-info btn-xs pull-right' %>
					</h3> 
				</div>
				<div class="panel-body">
			  	<table class="table table-bordered">
			  		<tbody>
			  			<tr>
			  				<th scope="row">Church</th>
			  				<td align="left"><%= user.church %>, <%= user.church_status %> 
			  				</td>
			  			</tr>
			  			<tr>
			  				<th scope="row">Interests</th>
			  				<td align="left"><%= user.interests %></td>
			  			</tr>
			  			<tr>
			  				<th scope="row">Being a Believer in City</th>
			  				<td align="left"><%= user.testimony %></td>
			  			</tr>
			  			<tr>
			  				<th scope="row">Why I Came to this City</th>
			  				<td align="left"><%= user.more_info %></td>
			  			</tr>
			  			<tr>
			  				<th scope="row">Relationship Status:</th>
			  				<td align="left"><%= user.status %></td>
			  			</tr>
			  			<tr>
			  				<th scope="row">Dating: What I'm Looking for:</th>
			  				<td align="left"><%= user.dating_pref %></td>
			  			</tr>
			  		</tbody>
					</table>
				</div>
  			<div class="panel-footer">
  				<div class="row"><%= image_tag user.avatar.url(:thumb), class: "img-thumbnail" %></div>
  				<p></p>
  				<div class="row">
						<% if user.is_female == true %>
							Female,
						<% else %>
							Male,
						<% end %>
							Age: <%= Time.now.utc.to_date.year - user.date_of_birth.year - (user.date_of_birth.to_date.change(:year => Time.now.utc.to_date.year) > Time.now.utc.to_date ? 1 : 0)%>,
								Height: <%= user.height / 12 %>'-<%= user.height % 12 %>"<br/>
								<b><%= link_to user.neighborhood, neighborhood_path(neighborhood: user.neighborhood) %></b>
					</div>
				</div>
			</div>
		<% end %>
		<%= will_paginate @user %>
	<% else %>
	<h1>welcome to ello</h1>	
	<p>join us today</p>
		<p>
			<%= link_to "Login", new_user_session_path, class: "btn btn-default btn-lg"%>
			<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg"%>
		</p>
	<% end %>
</div>

app/views/pages/feedback.html.erb
<div class="ui segment">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Help make 'ello' better</h3>
    </div>
    <div class="panel-body">
    	<div class="col-md-6">   
    		<%= render 'pages/googleform' %>
    	</div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron center">
	
	<% if user_signed_in? %>
		<h2>ello: everyone</h2>	
		<p></p>
  	<% @user.each do |user| %>
			<div class="panel panel-info">
				<div class="panel-heading">
					<h3 class="panel-title">
						<%= user.first_name %> <%= user.last_name[0,1] %>. <%= link_to 'Send Msg', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post', class: 'btn btn-info btn-xs pull-right' %>
					</h3> 
				</div>
				<div class="panel-body">
			  	<table class="table table-bordered">
			  		<tbody>
			  			<tr>
			  				<th scope="row">Church</th>
			  				<td align="left"><b><%= link_to user.church, church_path(church: user.church) %></b>, <%= user.church_status %> 
			  				</td>
			  			</tr>
			  			<tr>
			  				<th scope="row">Interests</th>
			  				<td align="left"><%= user.interests %></td>
			  			</tr>
			  			<tr>
			  				<th scope="row">Being a Believer in City</th>
			  				<td align="left"><%= user.testimony %></td>
			  			</tr>
			  			<tr>
			  				<th scope="row">Why I Came to this City</th>
			  				<td align="left"><%= user.more_info %></td>
			  			</tr>
			  			<tr>
			  				<th scope="row">Relationship Status:</th>
			  				<td align="left"><%= user.status %></td>
			  			</tr>
			  			<tr>
			  				<th scope="row">Dating: What I'm Looking for:</th>
			  				<td align="left"><%= user.dating_pref %></td>
			  			</tr>
			  		</tbody>
					</table>
				</div>
  			<div class="panel-footer">
  				<div class="row"><%= image_tag user.avatar.url(:thumb), class: "img-thumbnail" %></div>
  				<p></p>
  				<div class="row">
						<% if user.is_female == true %>
							Female,
						<% else %>
							Male,
						<% end %>
							Age: <%= Time.now.utc.to_date.year - user.date_of_birth.year - (user.date_of_birth.to_date.change(:year => Time.now.utc.to_date.year) > Time.now.utc.to_date ? 1 : 0)%>,
								Height: <%= user.height / 12 %>'-<%= user.height % 12 %>"<br/>
								<b><%= link_to user.neighborhood, neighborhood_path(neighborhood: user.neighborhood) %></b>
					</div>
				</div>
			</div>
		<% end %>
		<%= will_paginate @user %>
	<% else %>
	<h1>welcome to ello</h1>	
	<p>join us today</p>
		<p>
			<%= link_to "Login", new_user_session_path, class: "btn btn-default btn-lg"%>
			<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg"%>
		</p>
	<% end %>
</div>

<!-- <p>Find me in app/views/pages/home.html.erb</p> -->

app/views/pages/neighborhood.html.erb
<div class="jumbotron center">
	<% if user_signed_in? %>
		<h2>ello @ <%= params[:neighborhood] %></h2>	
		<p></p>
  	<% @user.each do |user| %>
			<div class="panel panel-info">
				<div class="panel-heading">
					<h3 class="panel-title">
						<%= user.first_name %> <%= user.last_name[0,1] %>. <%= link_to 'Send Msg', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post', class: 'btn btn-info btn-xs pull-right' %>
					</h3> 
				</div>
				<div class="panel-body">
			  	<table class="table table-bordered">
			  		<tbody>
			  			<tr>
			  				<th scope="row">Church</th>
			  				<td align="left"><b><%= link_to user.church, church_path(church: user.church) %></b>, <%= user.church_status %> 
			  				</td>
			  			</tr>
			  			<tr>
			  				<th scope="row">Interests</th>
			  				<td align="left"><%= user.interests %></td>
			  			</tr>
			  			<tr>
			  				<th scope="row">Being a Believer in City</th>
			  				<td align="left"><%= user.testimony %></td>
			  			</tr>
			  			<tr>
			  				<th scope="row">Why I Came to this City</th>
			  				<td align="left"><%= user.more_info %></td>
			  			</tr>
			  			<tr>
			  				<th scope="row">Relationship Status:</th>
			  				<td align="left"><%= user.status %></td>
			  			</tr>
			  			<tr>
			  				<th scope="row">Dating: What I'm Looking for:</th>
			  				<td align="left"><%= user.dating_pref %></td>
			  			</tr>
			  		</tbody>
					</table>
				</div>
  			<div class="panel-footer">
  				<div class="row"><%= image_tag user.avatar.url(:thumb), class: "img-thumbnail" %></div>
  				<p></p>
  				<div class="row">
						<% if user.is_female == true %>
							Female,
						<% else %>
							Male,
						<% end %>
							Age: <%= Time.now.utc.to_date.year - user.date_of_birth.year - (user.date_of_birth.to_date.change(:year => Time.now.utc.to_date.year) > Time.now.utc.to_date ? 1 : 0)%>,
								Height: <%= user.height / 12 %>'-<%= user.height % 12 %>"<br/>
								<%= user.neighborhood %>
					</div>
				</div>
			</div>
		<% end %>
		<%= will_paginate @user %>
	<% else %>
	<h1>welcome to ello</h1>	
	<p>join us today</p>
		<p>
			<%= link_to "Login", new_user_session_path, class: "btn btn-default btn-lg"%>
			<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg"%>
		</p>
	<% end %>
</div>