config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'
  get 'about' => 'pages#about'
  get 'feedback' => 'pages#feedback'
  get 'userprofiles/:id' => 'userprofiles#show', as: :userprofiles
  get 'admin' => 'admin#index'
  get 'users/:id/approve'=> 'users#approve_user', as: 'approve_user'
  get 'users/:id/unapprove'=> 'users#unapprove_user', as: 'unapprove_user'
  get 'church' => 'pages#church'
  get 'neighborhood' => 'pages#neighborhood'
  resources :conversations do
    resources :messages
  end

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "ello", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? && current_user && current_user.admin? && current_user.approved? %>
          <li><%= link_to "Admin", admin_path %></li>
        <% end %>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Inbox", conversations_path, class: "item" %></li>
          <li><%= link_to "Feedback", feedback_path %></li>
          <!-- <li><%= link_to "Settings", edit_user_registration_path %></li>-->
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <li class="navbar-text"><%= image_tag current_user.avatar.url(:small), class: "img-circle", width: "20" %> <em><%= current_user.first_name %></em></li>
          <li>
            <%= link_to edit_user_registration_path, class: "btn btn-default" do %>
              <i class="glyphicon glyphicon-cog"></i>
            <% end %>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>ello</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: "alert alert-info") %>
			<% end %>

			<%= yield %>
		</div>	

	</body>
</html>